# Generated by Django 5.2 on 2025-04-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagecinco',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagecuatro',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagedos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagetres',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageuno',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualitycinco',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualitycuatro',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualitydos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualitynueve',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualityocho',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualityseis',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualitysiete',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualitytres',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qualityuno',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.AddField(
            model_name='order',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Animales', 'Animales'), ('Arte Digital', 'Arte Digital'), ('Frases Motivadoras', 'Frases Motivadoras')], default='Animales', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(choices=[('Mate', 'Mate'), ('Brillante', 'Brillante')], default='Animales', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('Vinil', 'Vinil'), ('Papel Adhesivo', 'Papel Adhesivo'), ('Transparente', 'Transparente'), ('Holográfico', 'Holográfico'), ('Otro', 'Otro')], default='Vinil', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Producto desconocido', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
    ]
