# Generated by Django 5.2 on 2025-04-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_delete_task_remove_product_digital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
