# Generated by Django 5.2 on 2025-04-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
