# Generated by Django 5.2 on 2025-04-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_task_alter_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(default='Seila Camas', help_text='Nombre completo del receptor', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=9811234567, help_text='Número de teléfono de contacto', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='reference',
            field=models.TextField(blank=True, help_text='Indicaciones o referencias adicionales', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(help_text='Dirección principal', max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Provincia/Estado'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=20, verbose_name='Código Postal'),
        ),
    ]
