# Generated by Django 5.2 on 2025-05-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_delete_task_remove_order_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referencias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
