# Generated by Django 5.2 on 2025-05-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_personalizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='atendido',
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='respuesta_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('RESPONDIDA', 'Respondida')], default='PENDIENTE', max_length=20),
        ),
    ]
