# Generated by Django 5.2 on 2025-05-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_customer_date_of_birth_customer_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
